// Simple out and back autonomous  %71

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveTrain;
import edu.wpi.first.wpilibj2.command.WaitUntilCommand;
import edu.wpi.first.wpilibj.Timer;

import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.ParallelCommandGroup;

public class AutonomousCommand extends CommandBase {
    private final DriveTrain m_driveTrain;
    double startTime;

    public AutonomousCommand(DriveTrain subsystem) {
        m_driveTrain = subsystem;
        addRequirements(m_driveTrain);
    
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        startTime = edu.wpi.first.wpilibj.Timer.getFPGATimestamp();

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
    //     addCommands(

    //     new SequentialCommandGroup(
    
    //       new AutoScore(armSystem, clampSystem, m_drivetrainSubsystem),
    //       new DriveDistance( m_drivetrainSubsystem, -1.0 ).withTimeout(4.2),// backup about 4 meters <<<<<<<<<<<<<<
    //       new StowArms(armSystem))      
    //      );
    //   }
    
    double time = edu.wpi.first.wpilibj.Timer.getFPGATimestamp();

    if ((time - startTime) < 2.0)
        m_driveTrain.drive(0.6, 0);  // fwd 2 sec
        else if ((time - startTime) < 3.0)
        m_driveTrain.drive(0, 0); // stop 1 sec
        else if ((time - startTime) < 5.0)
        m_driveTrain.drive(-0.6, 0);  // bkw 2 sec
        else
        m_driveTrain.drive(0, 0);  // stop
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_driveTrain.drive(0, 0);  // stop
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
